#NEAF-63 Created population to number of accidents metric
itechartbigdatalab/NY-Accidents-Rate pull request #12
Opened 2019-05-23 14:04 UTC by VladimirBaklan

2019-05-23 14:50 UTC, sleshJdev requested changes

2019-05-23 14:50 UTC, sleshJdev commented on reports/.~lock.population_to_number_of_accidents_report.csv#
> +,uladzimir,wse-202-71a,23.05.2019 17:00,file:///home/uladzimir/.config/libreoffice/4;
What those files need for?

2019-05-23 14:50 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/Application.scala
> +  println("Population to number of accidents calculated")
Please, use dedicated logger

2019-05-23 14:50 UTC, sleshJdev commented on reports/.~lock.population_to_number_of_accidents_report.csv#
> +,uladzimir,wse-202-71a,23.05.2019 17:00,file:///home/uladzimir/.config/libreoffice/4;
I guess you pushed those files by accident

2019-05-23 14:50 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/parse/PopulationParser.scala
> -class PopulationParser @Inject()(districtsService: DistrictsService,
Why did you remove injection thru constructor? I guess it's more correct way of DI

2019-05-23 14:50 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/service/metric/PopulationMetricService.scala
> +      val districtHash = dat._1.hashCode()
Please, use pattern matching rather than manipulating with tuples: `dat._1, dat._2`

2019-05-23 14:50 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/service/PopulationService.scala
> +    population.population.toDouble / (population.area * NUMBER_NORMALIZATION_FACTOR)
It might potentially produce coefficient out of [0;1] range. Is it okay in your case? I'd prefer more robust and general way of normalization: `X(i) - Xmin / Xmax - Xmin`.

2019-05-23 15:21 UTC, VladimirBaklan commented on src/main/scala/com/itechart/ny_accidents/parse/PopulationParser.scala
> -class PopulationParser @Inject()(districtsService: DistrictsService,
When we use DI we get Spark serialization task exception, so, we need to use objects

2019-05-23 15:23 UTC, VladimirBaklan commented on src/main/scala/com/itechart/ny_accidents/service/PopulationService.scala
> +    population.population.toDouble / (population.area * NUMBER_NORMALIZATION_FACTOR)
It's ok. We multiply on this value just to increase situation with E-6 numbers

2019-05-23 15:24 UTC, VladimirBaklan commented on reports/.~lock.population_to_number_of_accidents_report.csv#
> +,uladzimir,wse-202-71a,23.05.2019 17:00,file:///home/uladzimir/.config/libreoffice/4;
Bad .gitignore config. Will remove it

2019-05-23 15:24 UTC, sleshJdev commented on reports/.~lock.population_to_number_of_accidents_report.csv#
> +,uladzimir,wse-202-71a,23.05.2019 17:00,file:///home/uladzimir/.config/libreoffice/4;
Thanks

2019-05-23 15:25 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/parse/PopulationParser.scala
> -class PopulationParser @Inject()(districtsService: DistrictsService,
Strange but ok, let's leave it as is.

2019-05-23 15:26 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/service/PopulationService.scala
> +    population.population.toDouble / (population.area * NUMBER_NORMALIZATION_FACTOR)
I see, thanks

2019-05-24 07:01 UTC, VladimirBaklan commented on src/main/scala/com/itechart/ny_accidents/Application.scala
> +  println("Population to number of accidents calculated")
Fixed

2019-05-24 07:07 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/Application.scala
> +  println("Population to number of accidents calculated")
Thanks

2019-05-24 07:12 UTC, sleshJdev approved these changes

2019-05-24 07:55 UTC, AlexKostritsa approved these changes

2019-05-24 07:55 UTC, merged