Neaf 82 migrate reports to postgresql
itechartbigdatalab/NY-Accidents-Rate pull request #35
Opened 2019-05-28 15:03 UTC by VladimirBaklan

2019-05-28 15:18 UTC, sleshJdev requested changes

2019-05-28 15:18 UTC, sleshJdev commented on reports/day_of_week.csv
> +4) Thu,529,100.0
?

2019-05-28 16:30 UTC, VladimirBaklan commented on reports/day_of_week.csv
> +4) Thu,529,100.0
Ooops. Gitignore updated :)

2019-05-28 20:16 UTC, sleshJdev requested changes

2019-05-28 20:16 UTC, sleshJdev commented on src/main/scala/com/itechart/ny_accidents/report/Reports.scala
> +      .withColumn(PK_DATAFRAME_NAME,monotonically_increasing_id())
Missed white space after comma, please format code.

2019-05-29 06:38 UTC, VladimirBaklan commented on src/main/scala/com/itechart/ny_accidents/report/Reports.scala
> +      .withColumn(PK_DATAFRAME_NAME,monotonically_increasing_id())
Formated

2019-05-29 08:06 UTC, sleshJdev approved these changes

2019-05-29 10:02 UTC, AlexKostritsa approved these changes

2019-05-29 10:03 UTC, merged